// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLr7dauWdaOOcuireLJTM08hKW6bry4G4',
    appId: '1:472483539179:web:fb2e07a0d10a974a0c76ae',
    messagingSenderId: '472483539179',
    projectId: 'pembayaranspp-46203',
    authDomain: 'pembayaranspp-46203.firebaseapp.com',
    storageBucket: 'pembayaranspp-46203.appspot.com',
    measurementId: 'G-TYTW6DV7KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeR80YzpWjfdOM7aZB1h7ExHn-9s0i8OY',
    appId: '1:472483539179:android:7b55875796024ff70c76ae',
    messagingSenderId: '472483539179',
    projectId: 'pembayaranspp-46203',
    storageBucket: 'pembayaranspp-46203.appspot.com',
  );
}
